#!/bin/bash

mkdir bower_components || rm -rf bower_components/mule-sdk-js
cd bower_components/
git clone git@github.com:nik0kin/mule-sdk-js
cd mule-sdk-js
git checkout v0.1.0
bower install
./dodev.sh
cd ../..
